name: doublepick2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  google_mobile_ads: ^5.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.3.0
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.0
  flutter_local_notifications: ^17.1.0
  device_info_plus: ^10.1.0
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1  # âœ… Dodano ovdje

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_firme.png
    - assets/images/lodoapp.png
    - ios/Runner/GoogleService-Info.plist

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lodoapp.png"
  adaptive_icon_background: "#90EE90"
  adaptive_icon_foreground: "assets/images/lodoapp.png"
